version: '3'
services:
  
  # traefik:
  #   image: traefik:latest
  #   command:
  #     - --api.insecure=true
  #     - --providers.docker=true
  #   ports:
  #     - "80:80"
  #     - "8080:8080"
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   networks:
  #     - backend

  # redis:
  #   image: redis:latest
  #   networks:
  #     - backend
  #   ports:
  #     - "6379"

  webapp:
    build: .
    networks:
      - backend
    ports:
      - "3000:3000"
      - "3001:3001"

  # webapp2:
  #   build: .
  #   networks:
  #     - backend
  #   ports:
  #     - "3003:3000"
  #     - "3004:3001"

  # webapp:
  #   build: .
  #   networks:
  #     - backend
    # depends_on:
    #   - redis
    # labels:
    #   - traefik.frontend.rule=Host:chatapp.localhost
    #   - traefik.backend=backend

  # webapp2:
  #   build: .
  #   networks:
  #     - backend
    # depends_on:
    #   - redis
    # labels:
    #   - traefik.frontend.rule=Host:chatapp.localhost
    #   - traefik.backend=backend

networks:
  backend:
