version: '3'
services:
  webapp:
    build: .
    ports:
      - 3000:3000
      - 3001:3001
    networks:
      - backend
    depends_on:
      - redis

  webapp2:
    build: .
    ports:
      - 3003:3000
      - 3004:3001
    networks:
      - backend
    depends_on:
      - redis

  redis:
    image: redis:latest
    networks:
      - backend
    ports:
      - "6379"

networks:
  backend:
